name = "bookmark-sync"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "bookmark-sync-db"
database_id = "5e928256-f77e-4a95-a5ed-988e96a3e09e"
